insert into actor_entity (id, name, nick_name) values(1, 'Roberto Gómez Bolaños', 'Chespirito');
insert into actor_entity (id, name, nick_name) values(2, 'Ramón Valdés', 'Dón Ramón');
insert into actor_entity (id, name, nick_name) values(3, 'Florinda Meza', 'Doña Florinda');
insert into actor_entity (id, name, nick_name) values(4, 'Carlos Villagrán', 'Quico');
insert into actor_entity (id, name, nick_name) values(5, 'MAria Antonieta de las Nieves', 'La Chilindrina');
insert into actor_entity (id, name, nick_name) values(6, 'Edgar Vivar', 'Ñoño');
insert into actor_entity (id, name, nick_name) values(7, 'Rubén Aguirre', 'El Profesor Jirafales');
insert into actor_entity (id, name, nick_name) values(8, 'Angelines Fernández', 'Doña Clotilde');
insert into actor_entity (id, name, nick_name) values(9, 'Horacio Gómez Bolaños', 'Godinez');
insert into actor_entity (id, name, nick_name) values(10, 'Raúl Padilla', 'Jaimito');